### ISSUE TITLE
Upgrade to Airflow 2.5.0: No module named airflow.providers.cncf.kubernetes.backcompat.pod / airflow.contrib.kubernetes

### ISSUE THREAD

**Issue by MiguelLsb** [ajbosco/dag-factory#148]
Failed to use dag-factory after loading latest Airflow Release 2.5.0.
Probably related to this:
Airflow config section kubernetes renamed to kubernetes_executor [(#26873)]
https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#airflow-config-section-kubernetes-renamed-to-kubernetes-executor-26873

Error message:
Broken DAG: [/opt/airflow/dags/custom_dags.py] Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/dagfactory/dagbuilder.py", line 40, in <module>
    from airflow.kubernetes.pod import Port
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/kubernetes/pod.py", line 32, in <module>
    from airflow.providers.cncf.kubernetes.backcompat.pod import Port, Resources  # noqa: autoflake
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.backcompat.pod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/dagfactory/dagfactory.py", line 12, in <module>
    from dagfactory.dagbuilder import DagBuilder
  File "/home/airflow/.local/lib/python3.7/site-packages/dagfactory/dagbuilder.py", line 48, in <module>
    from airflow.contrib.kubernetes.secret import Secret
ModuleNotFoundError: No module named 'airflow.contrib.kubernetes'

**Comment by Matheuskempa** [comment]
Same problem here.
