### ISSUE TITLE
Get the error "Broken DAG: [/usr/local/airflow/dags/example_dag_factory.py] No module named 'dagfactory'" in airflow UI

### ISSUE THREAD

**Issue by chongqiu-eng** [ajbosco/dag-factory#77]
I followed the instructions in the README file to install dag-factory in a local airflow container, in which the airflow version is 1.10.12 and python version is 3.8.9. 

I copied the files example_dag_factory.yml, example_dag_factory.py and print_hello.py in https://github.com/ajbosco/dag-factory/blob/master/examples into the folder /usr/local/airflow/dags in the container, expecting the DAGs defined in the yml file can be recognized. However, I see the following error in the airflow UI.

![image](https://user-images.githubusercontent.com/79876775/115396840-6fb0ae80-a1b3-11eb-9e9d-9127def7f54d.png)

Not sure what I missed. Any helps are appreciated.

**Comment by klimenkoIv** [comment]
Hello. Can you describe your container config? It seems, you didn't install "dagractory" to webserver instance container

**Comment by nk7983** [comment]
same issue here..I added it to the requirement.txt 

 ./mwaa-local-env test-requirements
Container amazon/mwaa-local:2.0.2 exists. Skipping build
Installing requirements.txt
Collecting dag-factory==0.7.2
  Downloading dag_factory-0.7.2-py2.py3-none-any.whl (10 kB)
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)

but getting 
Broken DAG: [/usr/local/airflow/dags/example_dag_factory.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/example_dag_factory.py", line 19, in <module>
    import dagfactory
ModuleNotFoundError: No module named 'dagfactory'

**Comment by dannylee8** [comment]
I faced a similar issue implementing Dagfactory in MWAA using Terraform.  We have multiple environments, with one env working fine and another that intermittently has this error message and DAGs will not show up.  Another issue is that the tasks will stop after every step, but will run fine if you clear it 2x.  

We eventually used the aws cli 2.0 tool to try and refresh the environment, but it failed because the MWAA couldnt access the version of requirements.txt.  We checked the S3 bucket for the hash that was indicated and it didnt exist.  We also discovered we had turned off versioning for the MWAA bucket.    This was likely after we created the first (no-problem) MWAA env and before we create the second (problem) MWAA env.  

The solution was to turn on the versioning, but the MWAA was locked in on this defunct/null version.  So what we had to do is point MWAA to a new requirements.txt file in a different folder of the same S3 bucket.  Once we did that the hash of the requirements.txt reset and the env. appears to be building from dagfactory fine.  One other thing we did was remove the top of the requirements file that had the constraints line.   I imagine we can add it back now, but leaving it alone for now since we do not have many requirements.

**Comment by shindeja** [comment]
Same issue for me also on MWAA 2.8.1 and dag-factory=0.19.0
``Broken DAG: [/usr/local/airflow/dags/example_dag_factory.py] Traceback (most recent call last): File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File``

**Comment by novandwiatmaja** [comment]
I also found this issue.

```
Broken DAG: [/opt/airflow/dags/repo/configs/load_dags.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/repo/configs/load_dags.py", line 2, in <module>
    from dagfactory import load_yaml_dags
ModuleNotFoundError: No module named 'dagfactory'
```

It seems that the DAG is failing to import the 'dagfactory' module, which is necessary for its execution. I believe this issue needs attention as it prevents the DAG from functioning properly.

Additional Information:

Airflow Version: 2.7.1
Dag Factory Version: 0.19.0

**Comment by diegopuints** [comment]
Hello, I get the same error I use the validate step the requirements file, it is my requirements file:

```
--constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.2/constraints-3.11.txt"

dag-factory==0.19.0
```

and my code:
```
from airflow import DAG
import dagfactory

config_file = "/usr/local/airflow/dags/test_factory.yml"
test_factory = dagfactory.DagFactory(config_file)

# Creating task dependencies
saludtotal_factory.clean_dags(globals())
saludtotal_factory.generate_dags(globals())
```

![imagen](https://github.com/user-attachments/assets/64b218b5-6929-44e7-bd46-3f5b10001aee)

Additional Information:

Airflow Version: 2.9.2, (i get the same error with 2.7.2)
Dag Factory Version: 0.19.0

**Comment by mp-spxl** [comment]
Any update on this?

**Comment by pankajastro** [comment]
If you are a MWAA customer there is specific way install these library discussed [here](https://github.com/astronomer/dag-factory/issues/77#issuecomment-1319584661). I'm closing this issue since this is specific to MWAA.
